spring:
  profiles:
    active: dev

   # MYSQL 连接
#  datasource:
#    url: jdbc:log4jdbc:mysql://192.168.6.113:3306/my_test?useUnicode=true&characterEncoding=utf8&useSSL=false
#    username: root
#    password: root
#    driver-class-name: net.sf.log4jdbc.DriverSpy

  # H2 连接
  datasource:
#    url: jdbc:h2:mem:test # 使用内存存储
    url: jdbc:p6spy:mysql://127.0.0.1:3306/jpa_test?useSSL=false
    username: root
    password: root
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
#    driver-class-name: org.h2.Driver
    hikari:
      maximum-pool-size: 13 #连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)
  # 开启控制台
  h2:
    console:
      # 开启控制台，默认为 /h2-console
      enabled: true
#      path: /console
      settings:
        web-allow-others: true

  ###### JPA配置【开始】 ######
  jpa:
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: create # create、create-drop、update、validate、none
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect  # 方言设置，默认为： MySQL5Dialect
  ###### JPA配置【结束】 ######


  jackson:
    default-property-inclusion: non_null
    date-format: "yyyy-MM-dd HH:mm:ss"
iba:
  kafka: 192.168.6.113:9092