spring:
  datasource:
    url: jdbc:h2:mem:test
#    url: jdbc:h2:file:~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
  h2:
    console:
      # 开启控制台，默认为 /h2-console
      enabled: true
      # 配置控制台路径
      path: /console

  output:
    ansi:
      enabled: always