spring:
  datasource:
    url: jdbc:p6spy:mysql://127.0.0.1:3306/jpa_test?useSSL=false
    username: root
    password: root
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver #com.mysql.jdbc.Driver
    schema: classpath:db/schema-mysql.sql
    data: classpath:db/data-mysql.sql
    initialization-mode: always
  #  datasource:
#    url: jdbc:mysql://192.168.6.113:3306/sync?useUnicode=true&characterEncoding=utf8&useSSL=false # 注意加上 useSSL=false
#    username: root
#    password: root
#    hikari:
#      maximum-pool-size: 9 #连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)

  jpa:
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: none # create、create-drop、update、validate、none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect  # 方言设置，默认就为MySQL5Dialect，或者MySQL5InnoDBDialect使用InnoDB引擎
    open-in-view: true

  ## DATA WEB 相关配置 {@link SpringDataWebProperties}
  data:
    web:
      pageable:
        default-page-size: 3 # 分页大小 默认为 20
#        page-parameter: pageNum # 当前页参数名 默认为 page
#        size-parameter: pageSize # 当前页参数名 默认为 size
#      sort:
#        sort-parameter: orderBy # 字段排序参数名 默认为 sort

  output:
    ansi:
      enabled: always
#  jackson:
#    default-property-inclusion: non_null
#    date-format: "yyyy-MM-dd HH:mm:ss"

server:
  compression:
    enabled: true
  port: 8080

