spring:
  datasource:
    url: jdbc:log4jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
    driver-class-name: net.sf.log4jdbc.DriverSpy #com.mysql.jdbc.Driver
    hikari:
      maximum-pool-size: 9 #连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)

  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: create-drop # create、create-drop、update、validate、none
  h2:
    console:
      # 开启控制台，默认为 /h2-console
      enabled: true
      settings:
        trace: true
      # 配置控制台路径
#      path: /console

  output:
    ansi:
      enabled: always

logging:
  pattern:
    console: "%clr{%d{yyyy-MM-dd HH:mm:ss.SSS}}{faint} | %clr{%5p} | %clr{%15.15t}{faint} | %clr{%-50.50c{1.}}{cyan} | %5L | %clr{%M}{magenta} | %msg%n%xwEx"
